MVC-Pratik-25-07/Entities/Concrete/School.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Pratik_25_07.Entities.Abstract;
using MVC_Pratik_25_07.Models.ModelMetaDataTypes;
using System.Collections.Generic;

namespace MVC_Pratik_25_07.Entities.Concrete
{
    [ModelMetadataType(typeof(SchoolVMMetaData))]
    public class School : BaseEntity
    {
        public School()
        {
            Students=new List<Student>();
           
        }
        public ICollection<Student> Students { get; set; }
      
    }
}

MVC-Pratik-25-07/Controllers/SchoolController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Pratik_25_07.Entities.Concrete;
using MVC_Pratik_25_07.Repositories.Abstract;

namespace MVC_Pratik_25_07.Controllers
{
    public class SchoolController : Controller
    {
        private readonly IRepository<School> schoolRepository;
        private readonly IRepository<Lesson> lessonRepository;

        public SchoolController(IRepository<School> schoolRepository, IRepository<Lesson> lessonRepository)
        {
            this.schoolRepository = schoolRepository;
            this.lessonRepository = lessonRepository;
        }
        public IActionResult Index()
        {
            var schools = schoolRepository.GetAll();
            return View(schools);
        }

        //Sschool/Create
        public IActionResult Create()
        {
            School school = new School();
            return View(school);       
        }
        [HttpPost]
        public IActionResult Create(School school)
        {
            if (!ModelState.IsValid)
            {
                var schools = schoolRepository.GetAll(); 
                return View(schools);
            }
            else
            {

            bool check;        

            check = schoolRepository.Add(school);

            if (check) return RedirectToAction(nameof(Index));
            else
            {
                ViewBag.Message = "Okul Eklenemedi!!!";

            }
            return View();
            }
        }

        //Get School
        public IActionResult Update(int id)
        {
            School school = schoolRepository.GetById(id);
            return View(school);
        }


        //Post:School to Update
        [HttpPost]
        public IActionResult Update(School school, int id)
        {
            bool check;
            school.Id = id;
            check = schoolRepository.Update(school);

            if (check) return RedirectToAction(nameof(Index));
            else
            {
                ViewBag.Message = "Öğrenci Eklenemedi!!!";
                return View(school);
            }
        }
        
        // Delete
        public IActionResult Delete(int id)
        {
            School school = schoolRepository.GetById(id);
            bool check;
            check = schoolRepository.Delete(school);
            if (check)
            {
                var schools = schoolRepository.GetAll();
                return View("Index", schools);
            }
            else
            {
                ViewBag.Message = "Okul Silinemez Öğrenciler var, Okulsuz mu Kalsın!!!";
                var schools = schoolRepository.GetAll();
                return View("Index", schools);

            }

        }
    }
}

MVC-Pratik-25-07/Views/School/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Create School";
}
@model School
<h1>Create School</h1>
<br />

<div asp-validation-summary="All" class="alert-danger">

</div>

<br />


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Name" class="contol-label"></label>
                <input asp-for="Name" class="form-control"/>
            </div>        
            <br />
             

            <br/>

             <div style="margin-top:10px" class="form-group">
               
                <input type="submit" value="Create" class="btn btn-primary"/>

            </div>

        </form>

    </div>

</div>

MVC-Pratik-25-07/Views/School/Index.cshtml
@{
    ViewData["Title"] = "Okullar Sayfası";
}


@model IEnumerable<School> ;



<div class="row">
    <div class="col-lg-4 offset-lg-4">   
         <div style="margin-bottom:5px">
          <a asp-action="Create" asp-controller="School"  class="btn btn-outline-info ">  Okul Ekle </a>

       </div> 
       
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Okul Adı</th>
                        <th>Ne zaman Oluşturuldu</th>
                                              

                    </tr>
                </thead>
                <tbody>
                  
                    @foreach (var item in Model)
                    {
                    <tr>                       
                        <td>@item.Id</td>
                        <td>@item.Name</td>
                        <td>@item.CreationTime</td>                                             
                        <td> <a asp-action="Update" asp-controller="School"class="btn btn-outline-info" asp-route-id="@item.Id"> Update</a></td>
                        <td> <a asp-action="Delete" asp-controller="School"class="btn btn-outline-info" asp-route-id="@item.Id"> Delete</a> 
                            </td>
                           

                        
                    </tr>  
                  
                    }
                    
                </tbody>
            </table>
    </div>
    <div>
        @if (@ViewBag.Message !=null)
       {
           @ViewBag.Message
       }
    </div>
</div>

MVC-Pratik-25-07/Views/School/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Update School";
}
@model School
<h1>Update School</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Update"asp-route-id="@Model.Id">
            <div class="form-group">
                <label asp-for="Name" class="contol-label"></label>
                <input asp-for="Name" class="form-control"/>
            </div>
             <div style="margin-top:10px" class="form-group">               
                <input type="submit" value="Update" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>