MVC-Pratik-25-07/Entities/Concrete/Lesson.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Pratik_25_07.Entities.Abstract;
using MVC_Pratik_25_07.Models.ModelMetaDataTypes;
using System.Collections.Generic;

namespace MVC_Pratik_25_07.Entities.Concrete
{
        [ModelMetadataType(typeof(LessonVMMetaData))]
    public class Lesson :BaseEntity
    {
        public Lesson()
        {
            Students=new List<Student>();
            
        }
        public ICollection<Student> Students { get; set; }
        
    }
}

MVC-Pratik-25-07/Controllers/LessonController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Pratik_25_07.Entities.Concrete;
using MVC_Pratik_25_07.Repositories.Abstract;

namespace MVC_Pratik_25_07.Controllers
{
    public class LessonController : Controller
    {
        private readonly IRepository<Lesson> lessonRepository;

        public LessonController(IRepository<Lesson> lessonRepository)
        {
            this.lessonRepository = lessonRepository;
        }
        public IActionResult Index()
        {
            var lesson = lessonRepository.GetAll();
            return View(lesson);
        }

        public IActionResult Create()
        {
            Lesson lesson = new Lesson();
            return View(lesson);
        }

        [HttpPost]
        public IActionResult Create(Lesson lesson)
        {
            if (!ModelState.IsValid)
            {
                
                return View(lesson);
            }
            else
            {
                bool check;
                check = lessonRepository.Add(lesson);

                if (check) return RedirectToAction(nameof(Index));
                else
                {
                    ViewBag.Message = "Ders Eklenemedi.";
                }
                return View();
            }
           
        }
        //Get LEsson
        public IActionResult Update(int id)
        {
            Lesson lesson = lessonRepository.GetById(id);
            return View(lesson);
        }

        //Post:Lesson to Update
        [HttpPost]
        public IActionResult Update(Lesson lesson, int id)
        {
            bool check;
            lesson.Id = id;
            check = lessonRepository.Update(lesson);

            if (check) return RedirectToAction(nameof(Index));
            else
            {
                ViewBag.Message = "Ders Eklenemedi!!!";
                return View(lesson);
            }
        }
        public IActionResult Delete(int id)
        {
            Lesson lesson = lessonRepository.GetById(id);
            bool check;
            check = lessonRepository.Delete(lesson);
            if (check)
            {
                var lessons = lessonRepository.GetAll();
                return View("Index", lessons);
            }
            else
            {
                ViewBag.Message = "Ders Silinemez Öğrenciler var, Derssiz mu Kalsın!!!";
                var lessons = lessonRepository.GetAll();
                return View("Index", lessons);

            }

        }
    }
}

MVC-Pratik-25-07/Views/Lesson/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Create Lesson";
}
 
<h1>Create Lesson</h1>
@model Lesson
<br />

<div asp-validation-summary="All" class="alert-danger">

</div>

<br />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" >
            <div class="form-group">
                <label asp-for="Name" class="contol-label"></label>
                <input asp-for="Name" class="form-control"/>
            </div>        
             <div style="margin-top:10px" class="form-group">
               
                <input type="submit" value="Create" class="btn btn-primary"/>

            </div>

        </form>

    </div>

</div>

MVC-Pratik-25-07/Views/Lesson/Index.cshtml
@{
    ViewData["Title"] = "Dersler Sayfası";
}


@model IEnumerable<Lesson> ;



<div class="row">
    <div class="col-lg-4 offset-lg-4">   
         <div style="margin-bottom:5px">
          <a asp-action="Create" asp-controller="Lesson"  class="btn btn-outline-info ">  Ders Ekle </a>

       </div> 
       
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Ders Adı</th>
                        <th>Ne zaman Oluşturuldu</th>
                                              

                    </tr>
                </thead>
                <tbody>
                  
                    @foreach (var item in Model)
                    {
                    <tr>                       
                        <td>@item.Id</td>
                        <td>@item.Name</td>
                        <td>@item.CreationTime</td>                            
                        <td> <a asp-action="Update" asp-controller="Lesson"class="btn btn-outline-info" asp-route-id="@item.Id"> Update</a></td>
                        <td> <a asp-action="Delete" asp-controller="Lesson"class="btn btn-outline-info" asp-route-id="@item.Id"> Delete</a> 
                            </td>

                        
                    </tr>  
                  
                    }
                    
                </tbody>
            </table>
    </div>
    <div>
        @if (@ViewBag.Message !=null)
       {
           @ViewBag.Message
       }
    </div>
</div>

MVC-Pratik-25-07/Views/Lesson/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Update Lesson";
}
@model Lesson
<h1>Update Lesson</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Update"asp-route-id="@Model.Id">
            <div class="form-group">
                <label asp-for="Name" class="contol-label"></label>
                <input asp-for="Name" class="form-control"/>
            </div>
             <div style="margin-top:10px" class="form-group">               
                <input type="submit" value="Update" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>